### PR TITLE
Add keys method

### PR DESCRIPTION
**Pull request by Vitaliy-Yakovchuk**
The extension does have a method to read all the keys from the shmt file, the new `keys` method will return all the keys

### CODE REVIEW

**Comment by alex-schneider** [comment]
Hello Vitaliy,
do you have an use-case for this method?

**Comment by Vitaliy-Yakovchuk** [comment]
Hello Alex,

Yes, we have many use cases (in myheritage.com).

One use case: we store metainformation about partitions by keys. There are cases where we need to find all the partitions on the cluster.

Another one: we store settings, often we need a list of all available settings.

Also, we keep translations in the SHMT files, and there is a procedure to deploy updated translations. This is an incremental procedure which involves only what was changed: [list of translations to update/list of translations], thus we need to merge translations on production with the updated information.

The workaround for the case is to have special _keys value, but this is less simple than just to call keys() method and require additional space.

**Comment by alex-schneider** [comment]
Would you please complete the README.md file with

```
diff --git a/README.md b/README.md
index 45aa853..be0630c 100644
--- a/README.md
+++ b/README.md
@@ -66,6 +66,13 @@ public (string|null) SHMT::get(string $string)
 * Returns the value if the key `$string` exists, otherwise `null`
 
 
+```
+public array SHMT::keys()
+```
+
+* Returns the list of all keys stored in the SHMT.
+
+
 ### Example
 
 Create a SHMT:
```

**Comment by Vitaliy-Yakovchuk** [comment]
Done!

**Comment by alex-schneider** [comment]
Thanks!

**Comment by Vitaliy-Yakovchuk** [comment]
Thank you for the project!

**Pull request merged**
